version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@4.1 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  CMake install: # name of your job
    executor:
      name: win/default # executor type
      #size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run:
          name: Download CMake
          command: |
            choco install cmake -y
      - run:
          name: Copy CMake
          command: |
            New-Item -Path ".\" -Name "CMake" -ItemType "directory"
            Copy-Item -Path "C:\Program Files\CMake\*" -Destination ".\CMake" -Recurse      
      - run:
          name: Check for CMake
          command: 
            ls '.\CMake\bin'
      - persist_to_workspace:
          root: .
          paths:
            - .
  build: # name of your job
    executor:
      name: win/default # executor type
      #size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      # Commands are run in a Windows virtual machine environment
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: run cmake
          command: |
            ls '.\CMake\bin'
            $env:PATH += ";.\CMake\bin"
<<<<<<< HEAD
<<<<<<< HEAD
            cmake -D CMAKE_BUILD_TYPE=Debug -S .\PacMan\ -B .\PacMAn\out\build\x64-debug
            cmake --build .\PacMan\out\build\x64-debug\
=======
            cmake -S .\PacMan\ -B .\PacMAn\out
            cmake --build .\PacMan\out --target ALL_BUILD --config Debug
>>>>>>> 816d3cffa6c6e3e6b1bbfb5c85563793e1b73253
=======
            cmake -D CMAKE_BUILD_TYPE=Debug -S .\PacMan\ -B .\PacMAn\out\build\x64-debug
            cmake --build .\PacMan\out\build\x64-debug\
>>>>>>> 262b42427c97c789b3ac2cd4ada40ebce569b432
      - persist_to_workspace:
          root: .
          paths:
            - .
  run: # name of your job
    executor:
      name: win/default # executor type
      #size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      - attach_workspace:
          at: .
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run:
          name: run PacMan
          command: |
<<<<<<< HEAD
<<<<<<< HEAD
            & C:\Users\circleci\project\PacMan\out\build\x64-debug\PacMan.exe
=======
            & C:\Users\circleci\project\PacMan\out\Debug\PacMan.exe
>>>>>>> 816d3cffa6c6e3e6b1bbfb5c85563793e1b73253
            
=======
            & C:\Users\circleci\project\PacMan\out\build\x64-debug\PacMan.exe
       
>>>>>>> 262b42427c97c789b3ac2cd4ada40ebce569b432
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - CMake install
      - build:
          requires:
            - CMake install
      - run:
          requires:
            - build