version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@4.1 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  CMake install: # name of your job
    executor:
      name: win/default # executor type
      #size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run:
          name: Download CMake
          command: |
            choco install cmake -y
      - run:
          name: Check for CMake
          command: 
            ls 'C:\Program Files\CMake\bin'
      - persist_to_workspace:
          root: .
          paths:
            - C:\Program Files\
  build: # name of your job
    executor:
      name: win/default # executor type
      #size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      # Commands are run in a Windows virtual machine environment
      - attach_workspace:
          at: C:\Program Files\
      - checkout
      - run:
          name: run cmake
          command: |
            ls 'C:\Program Files\CMake\bin'
            $env:PATH += ";C:\Program Files\CMake\bin"
            cmake -S .\PacMan\ -B .\PacMAn\out
            cmake --build .\PacMan\out --target ALL_BUILD --config Debug
      - persist_to_workspace:
          root: .
          paths:
            - .
  run: # name of your job
    executor:
      name: win/default # executor type
      #size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
    steps:
      - attach_workspace:
          at: .
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run:
          name: run PacMan
          command: |
            & C:\Users\circleci\project\PacMan\out\Debug\PacMan.exe
            
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - CMake install
      - build:
          requires:
            - CMake install
      - run:
          requires:
            - build